language: ruby
sudo: false
rvm:
  - 2.3.3

branches:
  - gh-pages

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --allow-hash-href --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
