# Site Settings
title: Compostage - Parc Libération à Grenoble
description: Informations générales sur le compostage collectif de la copropriété.
url: https://parc-liberation.github.io/compostage

# User Settings
username: Parc Libération
user_description: "Copropriété d'habitation."
github_username: parc-liberation

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

collections:
  articles:
    output: true
    permalink: /:title/

# Exclude Node.js related stuff
exclude: ['package.json', 'src', 'node_modules', 'dev']
